language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install g++-6 gcc-6 libpugixml-dev gawk wget tar
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - mkdir -p /tmp/dummy_for_patchelf/
  - wget 'https://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.bz2' -O /tmp/dummy_for_patchelf/patchelf.tar.bz2
  - cd /tmp/dummy_for_patchelf/ && tar xf /tmp/dummy_for_patchelf/patchelf.tar.bz2 && cd -
  - cd /tmp/dummy_for_patchelf/patchelf-0.9 && ./configure --prefix=/usr && make && sudo make install && cd -

script:
  - make BUILD=release appimage

after_success:
  - # curl --upload-file lilydumper*.AppImage https://transfer.sh/lilydumper-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./bin/lilydumper-*-x86_64.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
